name: Create diagram
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Update diagram
        uses: githubocto/repo-visualizer@main
        with:
          root_path: "core/src/main/java/io/questdb/griffin"
          excluded_paths: "ignore,.github,core/src/test,core/rust,core/src/main/resources,core/src/main/c,core/src/main/bin,core/src/main/assembly,benchmarks,ci,compat,artifacts,target,utils,i18n,pkg,win64svc,.idea"